#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN_G06)		+= capts.o focaltech5x06.o
obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN_G12_ANDA_M1005A)		+= capts.o focaltech5x06_g12anda.o
obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN_G12_ANDA_M805A)		+= capts.o focaltech5x06_g12anda.o
obj-$(CONFIG_IPS_BD7248F_TOUCHSCREEN) += ips_bd7248f.o
obj-$(CONFIG_IPS_BC8601_TOUCHSCREEN) += ips_bc8601.o
obj-$(CONFIG_GOODIX_GT801_CAPACITIVE_TOUCHSCREEN)		+= goodix_touch_gt819.o
obj-$(CONFIG_EGL_ASD_TOUCHSCREEN) += egalax_i2c.dat
obj-$(CONFIG_MG8698S_CAPACITIVE_TOUCHSCREEN) += mg8698s.o
obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN_G24)		+= capts.o focaltech_5x06_g24.o
obj-$(CONFIG_FOCALTECH_CAPACITIVE_TOUCHSCREEN_G06_E4)	+= focaltech5x06_g06e4.o
obj-$(CONFIG_NOVATEK_TOUCHSCREEN_NEW) += novatek_ts.o
obj-$(CONFIG_SSD25XX_CAPACITIVE_TOUCHSCREEN)		+= ssd253x-ts.o
obj-$(CONFIG_GOODIX_CHIP2_CAPACITIVE_TOUCHSCREEN) += goodix_touch_2chips.o
